/**
 * Medium engagement — warmup via reading, clapping, and human-like responses.
 *
 * Anti-detection is the #1 priority. All defaults are conservative:
 *   - 4-7 articles opened per session, with realistic 45-120s "reading" dwell
 *   - 2-4 claps per session (clap button clicked 1-3 times with jitter)
 *   - 0-2 responses per session, hard-capped at 4/day
 *   - Long inter-article cooldowns (30-90s; 60-150s after a comment)
 *   - Randomised topic + random offset into the tag feed (don't always hit top 6)
 *   - Dedup via data/medium-engaged.json (never engage same URL twice)
 *   - Daily caps persisted on disk (restart-safe)
 *   - Fallback to waitForHuman on the response editor when selectors drift
 *
 * Response ("comment") copy is generated by Claude Haiku with strict constraints:
 *   - Must reference a specific claim or line from the article
 *   - 1-3 sentences, no em-dashes, no "Great insights", no "As an AI"
 *   - Conversational developer register
 *
 * Usage (via --mode medium-engage in index.ts):
 *   node dist/index.js --mode medium-engage
 *   node dist/index.js --mode medium-engage --dry-run
 *   node dist/index.js --mode medium-engage --topic artificial-intelligence
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { generateContent } from '../../content/claude.js';
import { opinionsForPrompt } from '../../content/opinions.js';
import { antiPolish } from '../../content/anti-polish.js';
import {
  openTab,
  closeTab,
  waitForElement,
  executeScript,
  queryElements,
  getTabInfo,
  jitter,
  sleep,
} from './client.js';

/**
 * Map a Medium topic tag to a reader bucket so comments can pull a relevant
 * Nate opinion. Tech-ai is the default since medium-engage is dev-focused;
 * other buckets activate when the topic explicitly maps there.
 */
function topicToBucket(topic: string): string {
  const t = topic.toLowerCase();
  if (t.includes('life') || t.includes('mindful') || t.includes('self-improvement') || t.includes('relationships')) return 'life-reflection';
  if (t.includes('philosophy') || t.includes('psychology')) return 'philosophy-psychology';
  if (t.includes('humor') || t.includes('satire')) return 'humor-satire';
  if (t.includes('writing') || t.includes('creativity') || t.includes('fiction')) return 'creative-writing';
  if (t.includes('productivity') || t.includes('startup') || t.includes('business') || t.includes('economics')) return 'work-economics';
  return 'tech-ai';
}

// ─── Types ──────────────────────────────────────────────────────────────────

export interface MediumEngageConfig {
  claudeApiKey: string;
  dataDir: string;
  dryRun: boolean;
  /** Force a single topic instead of rotating. */
  topic?: string;
  /** Hard caps — all optional, conservative defaults applied. */
  maxReadPerSession?: number;
  maxClapPerSession?: number;
  maxCommentPerSession?: number;
  dailyCommentCap?: number;
  dailyClapCap?: number;
  /**
   * Verification mode — for step-1 smoke test of selectors + LLM path.
   * - Caps at 1 article (overrides session caps)
   * - Skips inter-article cooldowns and pre-session warmup
   * - Forces clap + comment attempt (overrides probability gates)
   * - Shortens simulated read dwell to ~15-30s (still tests scroll/selector resolution)
   * - Skips history write so you can re-run freely against the same article
   * Still performs real DOM work (scroll, scan, extract) and real LLM call.
   * Clap/response submit still gated by dryRun: verify+dryRun = simulate only,
   * verify without dryRun = actually click clap + actually try to post a response.
   */
  verify?: boolean;
}

export interface MediumEngageResult {
  topic: string;
  read: number;
  clapped: number;
  commented: number;
  skipped: string[];
  dailyTotals: { claps: number; comments: number };
}

interface EngagementEntry {
  date: string; // YYYY-MM-DD (UTC)
  url: string;
  title: string;
  action: 'read' | 'clap' | 'comment';
  claps?: number;
  comment?: string;
}

interface EngagementHistory {
  lastRunAt?: string;
  entries: EngagementEntry[];
}

// ─── Constants ──────────────────────────────────────────────────────────────

const HISTORY_FILE = 'medium-engaged.json';

// Broad topic pool. Rotated per session; recent topics biased down.
const TOPICS = [
  'artificial-intelligence',
  'programming',
  'philosophy',
  'writing',
  'fiction',
  'startup',
  'self-improvement',
  'life-lessons',
  'productivity',
  'technology',
];

const DEFAULTS = {
  maxReadPerSession: 6,
  maxClapPerSession: 4,
  maxCommentPerSession: 2,
  dailyCommentCap: 4,
  dailyClapCap: 6,
};

// Behaviour probabilities. Tuned for human-like ratios.
const CLAP_PROBABILITY = 0.65; // 65% of reads get a clap
const COMMENT_PROBABILITY = 0.4; // 40% of clapped articles get a comment (before caps)

// ─── History helpers ────────────────────────────────────────────────────────

function loadHistory(dataDir: string): EngagementHistory {
  const file = join(dataDir, HISTORY_FILE);
  if (!existsSync(file)) return { entries: [] };
  try {
    return JSON.parse(readFileSync(file, 'utf-8')) as EngagementHistory;
  } catch {
    return { entries: [] };
  }
}

function saveHistory(dataDir: string, history: EngagementHistory): void {
  writeFileSync(join(dataDir, HISTORY_FILE), JSON.stringify(history, null, 2));
}

function todayUTC(): string {
  return new Date().toISOString().split('T')[0];
}

function countToday(history: EngagementHistory, action: EngagementEntry['action']): number {
  const d = todayUTC();
  return history.entries.filter((e) => e.date === d && e.action === action).length;
}

function isAlreadyEngaged(history: EngagementHistory, url: string): boolean {
  return history.entries.some((e) => normaliseUrl(e.url) === normaliseUrl(url));
}

function normaliseUrl(url: string): string {
  // Strip tracking params + trailing slash for stable dedup
  try {
    const u = new URL(url);
    return `${u.origin}${u.pathname.replace(/\/$/, '')}`;
  } catch {
    return url.replace(/[?#].*$/, '').replace(/\/$/, '');
  }
}

// ─── Topic selection ────────────────────────────────────────────────────────

function pickTopic(history: EngagementHistory, forced?: string): string {
  if (forced && TOPICS.includes(forced)) return forced;
  if (forced) return forced; // allow off-list topics if explicitly requested

  // Bias away from topics used in the last 3 sessions
  const recent = history.entries.slice(-15).map((e) => extractTopicHint(e.url)).filter(Boolean);
  const weights = TOPICS.map((t) => (recent.includes(t) ? 0.4 : 1.0));
  const total = weights.reduce((s, w) => s + w, 0);
  let r = Math.random() * total;
  for (let i = 0; i < TOPICS.length; i++) {
    r -= weights[i];
    if (r <= 0) return TOPICS[i];
  }
  return TOPICS[0];
}

function extractTopicHint(url: string): string | null {
  // Medium URLs don't include tag, so this is a weak heuristic.
  // We only use topic bias when last-used topic was stored — punted for now.
  return null;
}

// ─── Article discovery ─────────────────────────────────────────────────────

interface ArticleRef {
  url: string;
  title: string;
}

async function collectArticles(tabId: number, limit: number): Promise<ArticleRef[]> {
  // Medium's tag pages render articles as <article> elements containing an <h2> title
  // and a link to the story. DOM shifts frequently — we cast a wide net.
  //
  // Member-only filter: Medium marks paywalled posts with a star SVG labelled
  // "Member-only story". We skip those because our engagement automation
  // (clap + comment) fails on paywalled bodies — the content is replaced with a
  // "This story is for members only" CTA and the interaction targets disappear.
  const script = `
    function isMemberOnly(article) {
      if (!article) return false;
      if (article.querySelector('[aria-label*="ember-only" i], [aria-label*="Member only" i]')) return true;
      var text = (article.textContent || '').toLowerCase();
      if (text.indexOf('member-only') !== -1) return true;
      if (text.indexOf('for members only') !== -1) return true;
      return false;
    }
    var seen = new Set();
    var out = [];
    var skippedMember = 0;
    // Broader net: walk every <article> on the page and pull the primary story link
    // from within it. Medium's anchor structure varies — sometimes /p/, sometimes
    // /@user/, sometimes /pub-name/. We'll filter by URL shape below.
    var articles = Array.from(document.querySelectorAll('article'));
    var articleCount = articles.length;
    for (var j = 0; j < articles.length; j++) {
      var article = articles[j];
      if (isMemberOnly(article)) { skippedMember++; continue; }
      // Collect all anchors in the card, prefer ones that look like a story link
      var links = Array.from(article.querySelectorAll('a[href]'));
      var href = '';
      for (var k = 0; k < links.length; k++) {
        var candidate = links[k].href || '';
        try { var u = new URL(candidate); candidate = u.origin + u.pathname; } catch (e) { continue; }
        // Story URLs end with -<hash> or include /p/<id>
        if (/-[a-f0-9]{8,}$/i.test(candidate) || /\\/p\\//.test(candidate)) {
          href = candidate;
          break;
        }
      }
      if (!href || seen.has(href)) continue;
      var titleEl = article.querySelector('h1, h2, h3');
      var title = titleEl ? (titleEl.textContent || '').trim() : '';
      if (title.length < 8) continue;
      seen.add(href);
      out.push({ url: href, title: title.slice(0, 200) });
      if (out.length >= ${limit * 3}) break;
    }
    return { refs: out, skippedMember: skippedMember, articleCount: articleCount };
  `;
  const result = await executeScript<{ refs: ArticleRef[]; skippedMember: number; articleCount: number } | ArticleRef[] | null>(
    tabId,
    script,
  );
  if (!result) return [];
  if (Array.isArray(result)) return result;
  console.log(
    `[Max] medium-engage: tag feed — ${result.articleCount} <article> elements, ${result.skippedMember} member-only filtered, ${result.refs.length} candidate(s)`,
  );
  return result.refs;
}

// ─── Reading simulation ────────────────────────────────────────────────────

/** Scroll the article tab in random increments to mimic a reader. */
async function simulateReading(tabId: number, verify = false): Promise<void> {
  // verify mode: 15-30s (enough for ~3-4 scrolls to exercise selectors, not enough to
  // burn test time). Normal: 45-120s (human-like dwell for anti-detection).
  const dwellMs = verify
    ? 15_000 + Math.floor(Math.random() * 15_000)
    : 45_000 + Math.floor(Math.random() * 75_000);
  const deadline = Date.now() + dwellMs;
  while (Date.now() < deadline) {
    const chunk = 250 + Math.floor(Math.random() * 600); // scroll 250-850 px
    await executeScript(
      tabId,
      `window.scrollBy({ top: ${chunk}, behavior: 'smooth' });`,
    ).catch(() => {});
    await jitter(verify ? 1500 : 3500, verify ? 4000 : 9000);
  }
}

/**
 * Extract title + first ~3000 chars of article body for comment grounding.
 * 3000 chars covers most Medium articles end-to-end (typical 600-1500 words ≈
 * 3500-9000 chars; first 3000 covers thesis + main argument + usually one
 * supporting section). Bumped from 1500 because closing-paragraph insights
 * were being missed in comments.
 */
async function extractArticleContent(tabId: number): Promise<{ title: string; excerpt: string }> {
  const data = await executeScript<{ title: string; excerpt: string } | null>(
    tabId,
    `
    var titleEl = document.querySelector('h1');
    var title = titleEl ? (titleEl.textContent || '').trim() : '';
    var article = document.querySelector('article');
    if (!article) return null;
    var paragraphs = Array.from(article.querySelectorAll('p')).map(function(p) { return (p.textContent || '').trim(); }).filter(Boolean);
    var excerpt = paragraphs.join(' ').slice(0, 3000);
    return { title: title, excerpt: excerpt };
    `,
  );
  return data ?? { title: '', excerpt: '' };
}

// ─── Recency check ─────────────────────────────────────────────────────────

/**
 * Returns false if the open article is older than maxAgeDays (default 180).
 * Medium renders a <time datetime="..."> in the article header — we parse that.
 * If no date is found we allow the article (fail-open is safer than over-filtering).
 */
async function isArticleRecent(tabId: number, maxAgeDays = 180): Promise<boolean> {
  const published = await executeScript<string | null>(
    tabId,
    `
    var t = document.querySelector('article time[datetime], time[datetime]');
    return t ? t.getAttribute('datetime') : null;
    `,
  ).catch(() => null);

  if (!published) return true; // no date found — allow
  const age = (Date.now() - new Date(published).getTime()) / 86_400_000;
  return age <= maxAgeDays;
}

// ─── Clap ───────────────────────────────────────────────────────────────────

/**
 * Click the clap button 1-3 times with natural jitter.
 * Medium's clap button lives inside the article footer. Selector has drifted
 * historically — we try a few options, log what we find on failure.
 */
async function clapArticle(tabId: number, dryRun: boolean): Promise<number> {
  const claps = 1 + Math.floor(Math.random() * 3); // 1-3 claps

  if (dryRun) {
    console.log(`[Max] medium-engage: DRY RUN — would clap ${claps}x`);
    return claps;
  }

  const ok = await executeScript<boolean>(
    tabId,
    `
    var btn = document.querySelector('button[aria-label*="clap" i]')
           || document.querySelector('button[data-testid*="clap" i]')
           || Array.from(document.querySelectorAll('button')).find(function(b) {
                var l = (b.getAttribute('aria-label') || '').toLowerCase();
                return l.indexOf('clap') !== -1 && l.indexOf('clapped') === -1;
              });
    if (!btn) return false;
    btn.scrollIntoView({ block: 'center', behavior: 'smooth' });
    return true;
    `,
  );

  if (!ok) {
    // Diagnostic: dump visible button aria-labels
    const btns = await queryElements(tabId, 'button', ['aria-label', 'data-testid'], 25).catch(() => []);
    const labels = btns
      .map((b) => b.attributes['aria-label'] || b.attributes['data-testid'])
      .filter(Boolean)
      .slice(0, 10)
      .join(' | ');
    console.warn(`[Max] medium-engage: clap button not found. Visible buttons: [${labels}]`);
    return 0;
  }

  await jitter(600, 1200);

  let success = 0;
  for (let i = 0; i < claps; i++) {
    const clicked = await executeScript<boolean>(
      tabId,
      `
      var btn = document.querySelector('button[aria-label*="clap" i]')
             || document.querySelector('button[data-testid*="clap" i]')
             || Array.from(document.querySelectorAll('button')).find(function(b) {
                  var l = (b.getAttribute('aria-label') || '').toLowerCase();
                  return l.indexOf('clap') !== -1 && l.indexOf('clapped') === -1;
                });
      if (!btn) return false;
      btn.click();
      return true;
      `,
    ).catch(() => false);
    if (clicked) success++;
    await jitter(450, 900); // human spacing between multi-claps
  }
  return success;
}

// ─── Comment generation ────────────────────────────────────────────────────

/**
 * Build the comment prompt with Nate's voice stack injected:
 *   • PERSONA line so it's a specific person, not "a thoughtful developer"
 *   • 1 relevant opinion from data/nate-opinions.json (bucket-matched to topic)
 *   • Existing hard rules (anti-AI-cliché, length, no em-dashes, imperfection)
 *
 * Keeps the prompt focused for a short reply — NOT the full post-generation
 * stack (no reading-insights, no notebook, no trends — those are wrong shape
 * for a 280-char response to someone else's article).
 */
const COMMENT_PROMPT = (title: string, excerpt: string, opinionsHint: string) => `
You are Nate Voss — an indie developer who writes with dry humor and genuine observation, not corporate helpfulness. Write a short reply to leave in the Responses section of this Medium article.

Article title: ${title}
Article excerpt: ${excerpt}
${opinionsHint}

Hard rules — breaking any = failure:
1. Reference a specific claim, example, or line from the article. No generic "great post" / "interesting read" / "well written".
2. 1-3 sentences, under 280 characters total.
3. No em-dashes (—). Use commas or periods instead.
4. No "As an AI". No "Great insights". No "This resonated with me". No "Thanks for sharing". No "Solid post".
5. Lowercase start is fine. Conversational register, not formal.
6. Do NOT start with the word "I" more than once across the whole reply.
7. Don't use hashtags, emojis, or exclamation marks.
8. Add one tiny imperfection: a mid-sentence thought shift, a casual aside, or a hesitation word like "kind of", "honestly", "not sure but".
9. The worldview stances above should SHAPE what you react to or how you frame it — do NOT quote them. If none of them fit this article cleanly, ignore them rather than forcing a fit.

Write ONLY the response text. No quotes, no preamble, no sign-off.
`.trim();

async function generateComment(
  apiKey: string,
  title: string,
  excerpt: string,
  dataDir: string,
  topic: string,
): Promise<string> {
  // 1-opinion injection (count=1 — comments are short, 2 stances would dominate)
  const bucket = topicToBucket(topic);
  const opinionsHint = opinionsForPrompt(dataDir, bucket, 1);

  let text = await generateContent(apiKey, COMMENT_PROMPT(title, excerpt, opinionsHint), {
    model: 'claude-haiku-4-5',
    temperature: 0.9,
    maxTokens: 120,
  });
  text = text.trim().replace(/^["']|["']$/g, '');

  // Anti-polish pass — strips corpspeak ("leverage"→"use"), transition spam,
  // hedge phrases, conclusion markers, remaining em-dashes. Platform='twitter'
  // is tightest (bullets stripped, em-dash max 1) — right for short replies.
  const polished = antiPolish(text, 'twitter');
  if (polished.changes.length > 0) console.log(`[Max] medium-engage: anti-polish fired: ${polished.changes.join(', ')}`);
  text = polished.text;

  // Belt-and-suspenders: hard-strip any surviving em-dashes
  text = text.replace(/—/g, ', ').replace(/\s{2,}/g, ' ');
  if (text.length > 280) text = text.slice(0, 277).trimEnd() + '...';
  return text;
}

// ─── Response posting ──────────────────────────────────────────────────────

/**
 * Attempt to post a response via Medium's inline response editor.
 * Returns:
 *   - { posted: true }  on success
 *   - { posted: false, humanAssisted: true } if we filled the text but the
 *     publish click failed and the user needs to finish in Brave
 *   - throws if editor could not be opened at all
 */
async function postResponse(
  tabId: number,
  comment: string,
  dryRun: boolean,
): Promise<{ posted: boolean; humanAssisted: boolean }> {
  if (dryRun) {
    console.log(`[Max] medium-engage: DRY RUN — would respond: "${comment}"`);
    return { posted: true, humanAssisted: false };
  }

  // Step 1: open the response SIDE PANEL.
  // Critical context (verified via screenshots 2026-04-20): Medium renders TWO
  // response UIs on article pages simultaneously:
  //   - Inline editor in the article body (placeholder varies, button "Publish"/"Reply")
  //   - Side panel that slides in from the right (placeholder "What are your thoughts?",
  //     button "Respond") — this is the one whose button actually publishes
  // Previously we were filling the inline editor while the side panel's "Respond"
  // button stayed disabled because ITS editor was empty. We now target the side panel.
  await executeScript(tabId, `window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });`).catch(() => {});
  await sleep(1500);
  // Priority order: (1) sticky-footer response icon, (2) responses count link,
  // (3) aria-label respond, (4) "write a response" text.
  const opened = await executeScript<boolean>(
    tabId,
    `
    var trigger = null;

    // Priority 1: sticky footer response/comment icon (anchored at bottom of viewport)
    var footerCandidates = Array.from(document.querySelectorAll(
      'button[aria-label*="respond" i], button[aria-label*="comment" i], a[aria-label*="respond" i]'
    ));
    for (var i = 0; i < footerCandidates.length; i++) {
      var btn = footerCandidates[i];
      var rect = btn.getBoundingClientRect();
      if (rect.bottom > window.innerHeight - 200 && rect.width > 0) {
        trigger = btn;
        break;
      }
    }

    // Priority 2: responses count link ("Responses (10)")
    if (!trigger) {
      trigger = Array.from(document.querySelectorAll('button, div[role="button"], a, span')).find(function(el) {
        var t = (el.textContent || '').trim();
        return /^responses?\\s*\\(\\d+\\)$/i.test(t);
      }) || null;
    }

    // Priority 3: any respond-labelled element
    if (!trigger) {
      trigger = document.querySelector('[data-testid="responseEditor"]')
             || document.querySelector('[aria-label*="respond" i]')
             || document.querySelector('[aria-label*="response" i]')
             || null;
    }

    // Priority 4: "write a response" text (opens inline editor as last resort)
    if (!trigger) {
      trigger = Array.from(document.querySelectorAll('button, div[role="button"], a, span')).find(function(el) {
        var t = (el.textContent || '').trim().toLowerCase();
        return t === 'write a response' || t.indexOf('write a response') === 0 || t === 'write a reply';
      }) || null;
    }

    if (!trigger) return false;
    trigger.scrollIntoView({ block: 'center', behavior: 'smooth' });
    trigger.click();
    return true;
    `,
  ).catch(() => false);

  if (!opened) {
    // Diagnostic: dump visible button/link text + aria labels so we can see what
    // Medium is actually rendering for the response section.
    const diag = await executeScript<{ labels: string[]; placeholders: string[] }>(
      tabId,
      `
      var seen = new Set();
      var labels = [];
      Array.from(document.querySelectorAll('button, a, div[role="button"]')).slice(0, 200).forEach(function(el) {
        var aria = (el.getAttribute('aria-label') || '').trim();
        var text = (el.textContent || '').trim().slice(0, 60);
        var key = aria + '|' + text;
        if (!seen.has(key) && (aria || text)) {
          seen.add(key);
          labels.push(aria ? '[aria=' + aria + '] ' + text : text);
        }
      });
      var placeholders = Array.from(document.querySelectorAll('[placeholder], [contenteditable="true"]'))
        .slice(0, 20)
        .map(function(el) {
          var p = el.getAttribute('placeholder') || '';
          var a = el.getAttribute('aria-label') || '';
          return (p || a || el.tagName).slice(0, 80);
        });
      return { labels: labels.slice(0, 30), placeholders: placeholders };
      `,
    ).catch(() => ({ labels: [], placeholders: [] }));
    console.error('[Max] medium-engage: response editor not found. Page surface:');
    console.error('  buttons/links (first 30):');
    diag.labels.forEach((l) => console.error('    ' + l));
    console.error('  editable/placeholder fields:');
    diag.placeholders.forEach((p) => console.error('    ' + p));
    throw new Error('medium-engage: could not open response editor (no matching element)');
  }

  // Let the side panel slide in and mount. Longer wait here — the panel animation
  // plus Slate editor hydration takes ~1.5-2.5s in practice.
  await jitter(2000, 3500);

  // Step 2a: locate the SIDE PANEL editor + Respond button, tag them with marker
  // attributes so subsequent steps (fill, submit) can find the same elements
  // deterministically. Approach: find the "Respond" button (unique to side panel —
  // inline uses "Publish"/"Reply"), walk up to the nearest ancestor containing a
  // contenteditable. Editor and button both live in the same panel subtree.
  const targeted = await executeScript<{ ok: boolean; diag: string }>(
    tabId,
    `
    function findSidePanelUI() {
      var respondBtns = Array.from(document.querySelectorAll('button')).filter(function(b) {
        if ((b.textContent || '').trim() !== 'Respond') return false;
        return b.offsetParent !== null;
      });
      for (var i = 0; i < respondBtns.length; i++) {
        var respond = respondBtns[i];
        var ancestor = respond.parentElement;
        while (ancestor && ancestor !== document.body) {
          var editor = ancestor.querySelector('[contenteditable="true"]');
          if (editor) return { editor: editor, respond: respond };
          ancestor = ancestor.parentElement;
        }
      }
      return null;
    }
    var ui = findSidePanelUI();
    if (!ui) {
      // Diagnostic dump — what editors + submit buttons ARE present
      var editors = Array.from(document.querySelectorAll('[contenteditable="true"]')).map(function(el) {
        var label = el.getAttribute('data-placeholder')
                 || el.getAttribute('aria-label')
                 || el.getAttribute('aria-placeholder')
                 || el.getAttribute('placeholder')
                 || '';
        return 'ce[' + label.slice(0, 50) + ']';
      });
      var submits = Array.from(document.querySelectorAll('button')).filter(function(b) {
        var t = (b.textContent || '').trim();
        return (t === 'Respond' || t === 'Publish' || t === 'Reply') && b.offsetParent !== null;
      }).map(function(b) {
        var dis = b.disabled || b.getAttribute('aria-disabled') === 'true';
        return b.textContent.trim() + (dis ? '(disabled)' : '(enabled)');
      });
      return { ok: false, diag: 'editors=' + JSON.stringify(editors) + ' submits=' + JSON.stringify(submits) };
    }
    ui.editor.setAttribute('data-pf-engage-target', '1');
    ui.respond.setAttribute('data-pf-engage-submit', '1');
    // Trigger Slate's onFocus via real mouse events at the editor's coordinates.
    // Plain .focus() is ignored by Slate's synthetic event system.
    var rect = ui.editor.getBoundingClientRect();
    var cx = rect.left + rect.width / 2;
    var cy = rect.top + Math.min(20, rect.height / 2);
    ['mousedown', 'mouseup', 'click'].forEach(function(type) {
      ui.editor.dispatchEvent(new MouseEvent(type, { bubbles: true, cancelable: true, clientX: cx, clientY: cy }));
    });
    ui.editor.focus();
    return { ok: true, diag: '' };
    `,
  ).catch((): { ok: boolean; diag: string } => ({ ok: false, diag: 'script-threw' }));

  if (!targeted.ok) {
    console.error('[Max] medium-engage: side-panel response UI not found.');
    if (targeted.diag) console.error('  diag: ' + targeted.diag);
    return { posted: false, humanAssisted: true };
  }

  // Let Slate register the focus event before inserting.
  await jitter(600, 1000);

  // Step 2b: fill the marked editor. Slate is a CONTROLLED component — it renders
  // from its internal model, not the DOM. execCommand('insertText') modifies the DOM
  // but may bypass Slate's model, leaving the Respond button disabled. We try two
  // mechanisms in order:
  //   1. ClipboardEvent('paste') — Slate has a first-class paste handler that updates
  //      its model directly from clipboardData.
  //   2. execCommand('insertText') — fallback that fires beforeinput/input events.
  const filled = await executeScript<boolean>(
    tabId,
    `
    var editor = document.querySelector('[data-pf-engage-target="1"]');
    if (!editor) return false;
    var text = ${JSON.stringify(comment)};

    editor.focus();

    // Place caret at start of editor's editable content.
    try {
      var sel = window.getSelection();
      var range = document.createRange();
      range.selectNodeContents(editor);
      range.collapse(true);
      sel.removeAllRanges();
      sel.addRange(range);
    } catch (e) {}

    // Attempt 1: synthetic paste event. Slate listens for this and updates its model.
    try {
      var dt = new DataTransfer();
      dt.setData('text/plain', text);
      var pasteEvt = new ClipboardEvent('paste', {
        bubbles: true,
        cancelable: true,
        clipboardData: dt,
      });
      // Some browsers ignore clipboardData in the constructor — define it explicitly.
      try { Object.defineProperty(pasteEvt, 'clipboardData', { value: dt }); } catch (e) {}
      editor.dispatchEvent(pasteEvt);
    } catch (e) {}

    // Attempt 2: if paste didn't land text, fall back to execCommand.
    if (editor.textContent.trim().length === 0) {
      document.execCommand('selectAll');
      document.execCommand('insertText', false, text);
    }

    return editor.textContent.length > 0;
    `,
  ).catch(() => false);

  if (!filled) {
    return { posted: false, humanAssisted: true };
  }

  // Slate needs a tick to run its state updater + re-render the toolbar/button state.
  await jitter(1500, 3000);

  // Step 3: click the marked Respond button. On failure, dump a diagnostic so we
  // can see whether the issue is: (a) our text isn't in the right editor, (b) the
  // editor isn't focused, or (c) Slate's model doesn't reflect the DOM text.
  const published = await executeScript<string | null>(
    tabId,
    `
    var btn = document.querySelector('[data-pf-engage-submit="1"]');
    if (!btn) {
      btn = Array.from(document.querySelectorAll('button')).find(function(b) {
        var t = (b.textContent || '').trim();
        return (t === 'Respond' || t === 'Publish' || t === 'Reply') && b.offsetParent !== null;
      }) || null;
    }
    if (!btn) return null;

    if (btn.disabled || btn.getAttribute('aria-disabled') === 'true') {
      // Capture ground-truth state for debugging
      var editor = document.querySelector('[data-pf-engage-target="1"]');
      var txt = editor ? (editor.textContent || '') : '';
      var active = document.activeElement;
      var activeTag = active ? active.tagName : 'none';
      var activeCE = active ? (active.getAttribute('contenteditable') || '-') : '-';
      var isTargetActive = editor === active;
      var editorCE = editor ? (editor.getAttribute('contenteditable') || '-') : '-';
      var slateAttrs = '';
      if (editor) {
        var s = [];
        ['data-slate-editor','data-slate-node','data-gramm'].forEach(function(a) {
          if (editor.hasAttribute(a)) s.push(a + '=' + editor.getAttribute(a));
        });
        slateAttrs = s.join(' ');
      }
      return 'disabled|txtLen=' + txt.length + '|txtStart=' + txt.slice(0,40).replace(/\\n/g,' ') + '|active=' + activeTag + '(ce=' + activeCE + ')|targetFocused=' + isTargetActive + '|editorCE=' + editorCE + '|slate=' + slateAttrs;
    }

    var label = (btn.textContent || '').trim();
    btn.click();
    return label;
    `,
  ).catch(() => null);

  if (!published || published === 'disabled' || (typeof published === 'string' && published.indexOf('disabled|') === 0)) {
    if (typeof published === 'string' && published.indexOf('disabled|') === 0) {
      console.log('[Max] medium-engage: publish button disabled — diagnostic: ' + published);
    } else {
      console.log('[Max] medium-engage: publish button missing/disabled — falling back to human finish');
    }
    return { posted: false, humanAssisted: true };
  }

  await sleep(2000);
  return { posted: true, humanAssisted: false };
}

// ─── Main orchestrator ─────────────────────────────────────────────────────

export async function engageMedium(config: MediumEngageConfig): Promise<MediumEngageResult> {
  if (config.verify) {
    console.log('[Max] medium-engage: VERIFY MODE — 1 article, no cooldowns, forced clap+comment, no history write');
  }

  const caps = config.verify
    ? { maxReadPerSession: 1, maxClapPerSession: 1, maxCommentPerSession: 1, dailyCommentCap: 99, dailyClapCap: 99 }
    : {
        maxReadPerSession: config.maxReadPerSession ?? DEFAULTS.maxReadPerSession,
        maxClapPerSession: config.maxClapPerSession ?? DEFAULTS.maxClapPerSession,
        maxCommentPerSession: config.maxCommentPerSession ?? DEFAULTS.maxCommentPerSession,
        dailyCommentCap: config.dailyCommentCap ?? DEFAULTS.dailyCommentCap,
        dailyClapCap: config.dailyClapCap ?? DEFAULTS.dailyClapCap,
      };

  const history = loadHistory(config.dataDir);
  const clapsToday = countToday(history, 'clap');
  const commentsToday = countToday(history, 'comment');

  if (clapsToday >= caps.dailyClapCap && commentsToday >= caps.dailyCommentCap) {
    console.log(
      `[Max] medium-engage: daily caps already hit (claps=${clapsToday}/${caps.dailyClapCap}, comments=${commentsToday}/${caps.dailyCommentCap}) — skipping`,
    );
    return {
      topic: '',
      read: 0,
      clapped: 0,
      commented: 0,
      skipped: ['daily-cap-hit'],
      dailyTotals: { claps: clapsToday, comments: commentsToday },
    };
  }

  const topic = pickTopic(history, config.topic);
  console.log(`[Max] medium-engage: topic=${topic} | today so far: ${clapsToday} claps, ${commentsToday} comments`);

  // Random pre-session warm-up delay (15-60s) so sessions don't all start on the minute.
  // Skipped in dry-run (no real actions to pace) and verify (smoke test, speed matters).
  if (!config.dryRun && !config.verify) {
    await jitter(15_000, 60_000);
  }

  const tagUrl = `https://medium.com/tag/${topic}`;
  console.log(`[Max] medium-engage: opening ${tagUrl}...`);
  const feedTab = await openTab(tagUrl);
  let articleReady = false;
  try {
    await waitForElement(feedTab.id, 'article', 45_000);
    articleReady = true;
  } catch {
    // waitForElement can time out a moment before the page finishes hydrating.
    // Do one last direct DOM check before giving up — if <article> is there now,
    // proceed. We saw this in practice: hasArticle:true in the diagnostic that
    // ran immediately after a waitForElement timeout.
    const articlePresent = await executeScript<boolean>(
      feedTab.id,
      `return !!document.querySelector('article');`,
    ).catch(() => false);
    if (articlePresent) {
      console.log(`[Max] medium-engage: waitForElement timed out but <article> is present — proceeding`);
      articleReady = true;
    }
  }
  if (!articleReady) {
    // Diagnostic: capture URL, title, and a body snippet so we can tell login wall
    // from selector drift from paywall redirect. Leave the tab open in verify mode
    // so the user can inspect it manually.
    const diag = await executeScript<{ url: string; title: string; bodyText: string; hasArticle: boolean; hasH1: boolean; signInText: boolean }>(
      feedTab.id,
      `var body = document.body ? (document.body.innerText || '').slice(0, 400) : '';
       return {
         url: location.href,
         title: document.title || '',
         bodyText: body,
         hasArticle: !!document.querySelector('article'),
         hasH1: !!document.querySelector('h1'),
         signInText: /sign.?in|sign.?up|get started|member.?only/i.test(body),
       };`,
    ).catch(() => null);
    if (diag) {
      console.error(`[Max] medium-engage: page diagnostic after timeout:`);
      console.error(`  url:         ${diag.url}`);
      console.error(`  title:       ${diag.title}`);
      console.error(`  hasArticle:  ${diag.hasArticle}  hasH1: ${diag.hasH1}`);
      console.error(`  signInText:  ${diag.signInText}  (true suggests login wall)`);
      console.error(`  bodyPreview: ${diag.bodyText.replace(/\s+/g, ' ').slice(0, 240)}`);
    }
    if (!config.verify) {
      await closeTab(feedTab.id).catch(() => {});
    } else {
      console.error('[Max] medium-engage: VERIFY — leaving tab open so you can inspect the page in Brave');
    }
    throw new Error(`medium-engage: tag page /tag/${topic} did not render articles within 45s`);
  }
  await jitter(2500, 5000); // let feed settle

  // Scroll the feed a bit before picking — a real user scans before clicking
  await executeScript(
    feedTab.id,
    `window.scrollBy({ top: ${500 + Math.floor(Math.random() * 1200)}, behavior: 'smooth' });`,
  ).catch(() => {});
  await jitter(1500, 3000);

  const refs = await collectArticles(feedTab.id, caps.maxReadPerSession);
  await closeTab(feedTab.id).catch(() => {});

  // Dedup against history, shuffle, random offset
  const fresh = refs.filter((r) => !isAlreadyEngaged(history, r.url));
  if (fresh.length === 0) {
    console.log(`[Max] medium-engage: no fresh articles found for ${topic} (all already engaged)`);
    return {
      topic,
      read: 0,
      clapped: 0,
      commented: 0,
      skipped: ['no-fresh-articles'],
      dailyTotals: { claps: clapsToday, comments: commentsToday },
    };
  }

  // Random offset + cap. Don't always start at index 0.
  const startIdx = Math.min(Math.floor(Math.random() * 3), Math.max(0, fresh.length - caps.maxReadPerSession));
  const picks = fresh.slice(startIdx, startIdx + caps.maxReadPerSession);

  const result: MediumEngageResult = {
    topic,
    read: 0,
    clapped: 0,
    commented: 0,
    skipped: [],
    dailyTotals: { claps: clapsToday, comments: commentsToday },
  };

  for (let i = 0; i < picks.length; i++) {
    const article = picks[i];

    // Re-check caps before each article
    if (result.clapped >= caps.maxClapPerSession && result.commented >= caps.maxCommentPerSession) {
      console.log(`[Max] medium-engage: session caps reached — stopping early`);
      break;
    }

    console.log(`[Max] medium-engage: [${i + 1}/${picks.length}] ${article.title.slice(0, 70)}`);
    let tab;
    try {
      tab = await openTab(article.url);
    } catch (err) {
      console.warn(`[Max] medium-engage: failed to open ${article.url} — ${(err as Error).message}`);
      result.skipped.push(article.url);
      continue;
    }

    try {
      await waitForElement(tab.id, 'article', 15_000);
    } catch {
      console.warn(`[Max] medium-engage: article did not load, skipping`);
      result.skipped.push(article.url);
      await closeTab(tab.id).catch(() => {});
      continue;
    }

    // Second-tier paywall check: if the article is member-only and we're not a
    // member, the body is replaced with a "This story is for members only" CTA
    // and clap/comment targets disappear. Skip rather than waste a slot.
    const paywalled = await executeScript<boolean>(
      tab.id,
      `var text = (document.body ? document.body.innerText : '').toLowerCase();
       if (text.indexOf('this story is for members only') !== -1) return true;
       if (text.indexOf('member-only story') !== -1) return true;
       if (document.querySelector('[aria-label*="ember-only" i]')) return true;
       return false;`,
    ).catch(() => false);
    if (paywalled) {
      console.warn(`[Max] medium-engage: article is member-only (paywall), skipping`);
      result.skipped.push(article.url);
      await closeTab(tab.id).catch(() => {});
      continue;
    }

    // Recency check — skip articles older than 6 months (180 days).
    // Authors of stale posts are unlikely to still be active or to notice engagement.
    const recent = await isArticleRecent(tab.id, 180);
    if (!recent) {
      console.log(`[Max] medium-engage: article older than 180 days — skipping`);
      result.skipped.push(article.url);
      await closeTab(tab.id).catch(() => {});
      continue;
    }

    await jitter(config.verify ? 500 : 2000, config.verify ? 1500 : 4500);

    // Simulate reading
    await simulateReading(tab.id, config.verify);

    // Record the read
    result.read++;
    history.entries.push({
      date: todayUTC(),
      url: article.url,
      title: article.title,
      action: 'read',
    });

    // Decide clap
    const dailyClapsRemaining = caps.dailyClapCap - (clapsToday + result.clapped);
    const sessionClapsRemaining = caps.maxClapPerSession - result.clapped;
    const canClap = dailyClapsRemaining > 0 && sessionClapsRemaining > 0;
    // verify mode forces a clap attempt so the clap selector gets exercised every run
    const willClap = canClap && (config.verify || Math.random() < CLAP_PROBABILITY);

    let clapsThisArticle = 0;
    if (willClap) {
      clapsThisArticle = await clapArticle(tab.id, config.dryRun);
      if (clapsThisArticle > 0) {
        result.clapped++;
        history.entries.push({
          date: todayUTC(),
          url: article.url,
          title: article.title,
          action: 'clap',
          claps: clapsThisArticle,
        });
        console.log(`[Max] medium-engage: clapped ${clapsThisArticle}x`);
      }
    }

    // Decide comment (only if we clapped successfully)
    const dailyCommentsRemaining = caps.dailyCommentCap - (commentsToday + result.commented);
    const sessionCommentsRemaining = caps.maxCommentPerSession - result.commented;
    // verify mode forces comment attempt even without a successful clap — we need the
    // comment path exercised regardless of whether the clap selector is currently working.
    const canComment = config.verify
      ? dailyCommentsRemaining > 0 && sessionCommentsRemaining > 0
      : clapsThisArticle > 0 && dailyCommentsRemaining > 0 && sessionCommentsRemaining > 0;
    const willComment = canComment && (config.verify || Math.random() < COMMENT_PROBABILITY);

    if (willComment) {
      try {
        const { title, excerpt } = await extractArticleContent(tab.id);
        if (excerpt.length < 300) {
          console.log(`[Max] medium-engage: excerpt too short (${excerpt.length} chars), skipping comment`);
        } else {
          const comment = await generateComment(config.claudeApiKey, title || article.title, excerpt, config.dataDir, topic);
          console.log(`[Max] medium-engage: generated comment — "${comment.slice(0, 80)}${comment.length > 80 ? '...' : ''}"`);

          const { posted, humanAssisted } = await postResponse(tab.id, comment, config.dryRun);
          if (posted) {
            result.commented++;
            history.entries.push({
              date: todayUTC(),
              url: article.url,
              title: article.title,
              action: 'comment',
              comment,
            });
            console.log(`[Max] medium-engage: response posted${humanAssisted ? ' (human-assisted)' : ''}`);
          } else if (humanAssisted) {
            // Text is in the editor but publish click didn't fire — wait for the human.
            console.log(`[Max] medium-engage: response filled but not published. Finish in Brave. Waiting up to 3 min...`);
            const deadline = Date.now() + 3 * 60_000;
            let finished = false;
            while (Date.now() < deadline) {
              await sleep(4000);
              // Poll: if the response text no longer appears as editable, assume it was posted
              const stillEditing = await executeScript<boolean>(
                tab.id,
                `var eds = Array.from(document.querySelectorAll('[contenteditable="true"]'));
                 return eds.some(function(e) { return (e.textContent || '').indexOf(${JSON.stringify(comment.slice(0, 40))}) !== -1; });`,
              ).catch(() => true);
              if (!stillEditing) { finished = true; break; }
            }
            if (finished) {
              result.commented++;
              history.entries.push({
                date: todayUTC(),
                url: article.url,
                title: article.title,
                action: 'comment',
                comment,
              });
              console.log(`[Max] medium-engage: response confirmed posted (human-assisted)`);
            } else {
              console.log(`[Max] medium-engage: response not confirmed within 3 min — moving on`);
            }
          }
        }
      } catch (err) {
        console.warn(`[Max] medium-engage: comment step failed — ${(err as Error).message}`);
      }
    }

    await closeTab(tab.id).catch(() => {});

    // Cooldown before next article. Longer after commenting. Skipped in verify mode
    // (we only engage 1 article anyway, and smoke tests should be fast).
    if (i < picks.length - 1 && !config.verify) {
      const lower = willComment ? 60_000 : 30_000;
      const upper = willComment ? 150_000 : 90_000;
      console.log(`[Max] medium-engage: cooldown ${Math.round(lower / 1000)}-${Math.round(upper / 1000)}s...`);
      await jitter(lower, upper);
    }
  }

  // Save history (always, even on partial completion). Skipped in verify mode so
  // repeated smoke tests don't pollute the dedup list and can target the same article.
  if (!config.verify) {
    history.lastRunAt = new Date().toISOString();
    saveHistory(config.dataDir, history);
  } else {
    console.log('[Max] medium-engage: VERIFY — skipping history write');
  }

  result.dailyTotals = {
    claps: clapsToday + result.clapped,
    comments: commentsToday + result.commented,
  };

  console.log(
    `[Max] medium-engage: done — read=${result.read} clapped=${result.clapped} commented=${result.commented} ` +
      `| today totals: ${result.dailyTotals.claps} claps, ${result.dailyTotals.comments} comments`,
  );
  return result;
}
