/**
 * Content calendar — weekly plan generated by Gemini.
 * Saved to data/calendar.json, consumed by the scheduler.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { generateContent } from './gemini.js';
import type { ContentCategory } from './templates.js';
import type { WarmupStage } from './scheduler.js';

export interface CalendarDay {
  date: string; // YYYY-MM-DD
  twitter: ContentCategory | null;
  devto: ContentCategory | null;
  twitterAngle?: string; // brief note on the specific angle
  devtoAngle?: string;
}

export interface WeeklyCalendar {
  weekOf: string; // Monday YYYY-MM-DD
  generatedAt: string;
  stage: WarmupStage;
  days: CalendarDay[];
}

const CALENDAR_FILE = 'calendar.json';

export function loadCalendar(dataDir: string): WeeklyCalendar | null {
  const file = join(dataDir, CALENDAR_FILE);
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, 'utf-8'));
  } catch {
    return null;
  }
}

export function saveCalendar(dataDir: string, calendar: WeeklyCalendar): void {
  writeFileSync(join(dataDir, CALENDAR_FILE), JSON.stringify(calendar, null, 2));
}

/** Get Monday of the current week (UTC). */
function currentMonday(): string {
  const now = new Date();
  const day = now.getUTCDay(); // 0=Sun, 1=Mon, ...
  const diff = day === 0 ? -6 : 1 - day;
  const monday = new Date(now);
  monday.setUTCDate(now.getUTCDate() + diff);
  return monday.toISOString().split('T')[0];
}

/** Check if the calendar is for this week. */
export function isCalendarCurrent(calendar: WeeklyCalendar | null): boolean {
  if (!calendar) return false;
  return calendar.weekOf === currentMonday();
}

/** Get today's plan from the calendar. Returns null if today isn't in the calendar. */
export function getTodayFromCalendar(calendar: WeeklyCalendar): CalendarDay | null {
  const today = new Date().toISOString().split('T')[0];
  return calendar.days.find((d) => d.date === today) ?? null;
}

const GENERATION_PROMPT = (stage: WarmupStage, mondayDate: string) => `You are planning a week of content for PromptFuel, a free open-source token optimization toolkit for LLM applications. The persona is Nate Voss (@natevoss), an indie developer.

Current warmup stage: ${stage}

Content categories available: tip, comparison, tutorial, stats, launch, opinion
${stage === 'warmup' ? 'NOTE: During warmup, do NOT use the "stats" category — the account is too new for metrics-bragging to look authentic.' : ''}

Posting schedule for ${stage} stage:
- Twitter: 1 post/day (every day)
- Dev.to: ${stage === 'warmup' ? '1 article on Tuesday' : stage === 'transition' ? '2 articles on Tuesday and Thursday' : '3 articles on Monday, Wednesday, Friday'}

Generate a 7-day content calendar starting from ${mondayDate} (Monday) through the following Sunday.

Rules:
- Vary the categories — no more than 2 of the same category in a row for Twitter
- Each entry should have a brief "angle" (1 sentence) describing the specific take or topic
- Dev.to entries should be null on non-posting days
- Twitter should have a category every day

Respond in EXACTLY this JSON format, nothing else:
[
  {"date":"YYYY-MM-DD","twitter":"category","devto":"category_or_null","twitterAngle":"brief angle","devtoAngle":"brief angle or null"},
  ...7 entries
]`;

export async function generateWeeklyCalendar(
  geminiApiKey: string,
  stage: WarmupStage,
  dataDir: string,
): Promise<WeeklyCalendar> {
  const monday = currentMonday();

  console.log(`[Max] Generating content calendar for week of ${monday}...`);
  const raw = await generateContent(geminiApiKey, GENERATION_PROMPT(stage, monday), {
    temperature: 0.8,
    maxTokens: 1000,
  });

  let days: CalendarDay[];
  try {
    let cleaned = raw.trim();
    if (cleaned.startsWith('```')) {
      cleaned = cleaned.replace(/^```[\w]*\n?/, '').replace(/\n?```$/, '');
    }
    const parsed = JSON.parse(cleaned);
    days = parsed.map((d: any) => ({
      date: d.date,
      twitter: d.twitter || null,
      devto: d.devto || null,
      twitterAngle: d.twitterAngle || undefined,
      devtoAngle: d.devtoAngle || undefined,
    }));
  } catch {
    console.warn('[Max] Calendar generation parse failed — using fallback rotation');
    days = generateFallbackCalendar(monday, stage);
  }

  const calendar: WeeklyCalendar = {
    weekOf: monday,
    generatedAt: new Date().toISOString(),
    stage,
    days,
  };

  saveCalendar(dataDir, calendar);
  console.log(`[Max] Calendar saved: ${days.length} days planned`);

  return calendar;
}

/** Deterministic fallback if Gemini fails to generate a valid calendar. */
function generateFallbackCalendar(monday: string, stage: WarmupStage): CalendarDay[] {
  const categories: ContentCategory[] = ['tip', 'comparison', 'tutorial', 'launch', 'opinion', 'tip', 'comparison'];
  const devtoDays = stage === 'warmup' ? [1] : stage === 'transition' ? [1, 3] : [0, 2, 4]; // indices in week

  const days: CalendarDay[] = [];
  const base = new Date(monday + 'T00:00:00Z');

  for (let i = 0; i < 7; i++) {
    const d = new Date(base);
    d.setUTCDate(base.getUTCDate() + i);
    days.push({
      date: d.toISOString().split('T')[0],
      twitter: categories[i],
      devto: devtoDays.includes(i) ? categories[(i + 2) % categories.length] : null,
    });
  }

  return days;
}
